[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Branch Deploy context: all deploys that are not from
# a pull/merge request or from the Production branch 
# will inherit these settings.
[context.branch-deploy.environment]
  NODE_ENV = "development"
