version: 2.1
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          key: node-deps-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: node-deps-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install SWC for linux arch
          command: npm install @next/swc-linux-x64-gnu
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
