import Head from 'next/head';

import { ethers } from 'ethers';

console.log(ethers);

export default function Home() {
	return (
		<div>
			<Head>
				<title>NomadHouse Home Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="text-3xl font-bold underline">Welcome to NomadHouse</h1>
				{/* eslint-disable-next-line react/no-unescaped-entities */}
				<p>Let's rock the Chainlink Hackathon!</p>
			</main>

			<footer>Powered by NomadHouse</footer>
		</div>
	);
}
